### ISSUE TITLE
patched?

### ISSUE THREAD

**Issue by EmisThePro1stLT** [YABOIpy/DTG#2]
crashes

**Comment by YABOIpy** [comment]
![image](https://github.com/YABOIpy/DTG/assets/110062350/23c93b29-7ca4-450c-8539-d59bc10f7c30)
please learn how to read.

**Comment by EmisThePro1stLT** [comment]
ive added proxies, setup config file with capsolver key, it doesnt work

**Comment by EmisThePro1stLT** [comment]
after entering the discord link it just crashes

**Comment by YABOIpy** [comment]
No error msg?

**Comment by EmisThePro1stLT** [comment]
i tried at first it displayed some error msg now nothing
